language: node_js
node_js:
- '0.10'
script: npm run test_travis
after_success:
- npm run coverage_travis
env:
  global:
    secure: UUXJPOUQZBxYbGvkGJ0jTrWNwxDiG1x0hOvE4StMVgKQKUsbs0MV3s9uiTFdprT6XWTm6Jn+YqORLVNN4lNf7BP9MzkKOE4bDwd0koZ0LeATueu7HlzTBE7yk4XD3sI8460VEUPaj5QR33+O1UJ7Yuqslv9XKfoee24te3VOSMs=
